apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulceo-service-manager

spec:
  rules:
    - http:
        paths:
          - path: /api/v1/tasks
            pathType: Prefix
            backend:
              service:
                name: pulceo-service-manager
                port:
                  number: 7979
          - path: /api/v1/applications
            pathType: Prefix
            backend:
              service:
                name: pulceo-service-manager
                port:
                  number: 7979
          - path: /psm/health
            pathType: Exact
            backend:
              service:
                name: pulceo-service-manager
                port:
                  number: 7979

---
apiVersion: v1
kind: Service
metadata:
  name: pulceo-service-manager

spec:
  ports:
    - protocol: TCP
      name: web
      port: 7979
  selector:
    app: pulceo-service-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulceo-service-manager
  labels:
    app: pulceo-service-manager

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulceo-service-manager
  template:
    metadata:
      labels:
        app: pulceo-service-manager
    spec:
      containers:
        - name: pulceo-service-manager
          image: ghcr.io/spboehm/pulceo-service-manager:v1.3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: psm-pv-db
              mountPath: /db
          env:
            - name: PRM_HOST
              valueFrom:
                configMapKeyRef:
                  name: psm-configmap
                  key: PRM_HOST
            - name: PNA_MQTT_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: psm-credentials
                  key: PNA_MQTT_BROKER_URL
            - name: PNA_MQTT_CLIENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: psm-credentials
                  key: PNA_MQTT_CLIENT_USERNAME
            - name: PNA_MQTT_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psm-credentials
                  key: PNA_MQTT_CLIENT_PASSWORD
          ports:
            - containerPort: 7979
              name: web
      volumes:
        - name: psm-pv-db
          persistentVolumeClaim:
            claimName: psm-pv-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psm-pv-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
